.TH "BleedAttack" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BleedAttack
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSkill\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBFunction\fP (\fBEntity\fP *target, \fBEntity\fP *attacker, \fBRandom\fP *random) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
