.TH "Button" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Button
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBClickable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBButton\fP (float x, float y, std::string type)"
.br
.ti -1c
.RI "void \fBSetAdditionalTexture\fP (std::string name)"
.br
.ti -1c
.RI "void \fBRender\fP (sf::RenderTarget *target)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBadditionalTextureSet\fP"
.br
.ti -1c
.RI "int \fBoffset\fP"
.br
.ti -1c
.RI "std::string \fBtype\fP"
.br
.ti -1c
.RI "sf::Sprite \fBadditionalSprite\fP"
.br
.ti -1c
.RI "sf::Texture \fBadditionalTexture\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
