.TH "Clickable" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clickable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBButton\fP, and \fBUnitFrame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRender\fP (sf::RenderTarget *target)"
.br
.ti -1c
.RI "void \fBUpdate\fP (const sf::Vector2f mousePos)"
.br
.ti -1c
.RI "const bool \fBisPressed\fP ()"
.br
.ti -1c
.RI "void \fBSetButtonState\fP (bool state)"
.br
.ti -1c
.RI "\fBClickable\fP (float x, float y)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBpngSuffix\fP = '\&.png'"
.br
.ti -1c
.RI "short unsigned \fBbuttonState\fP"
.br
.ti -1c
.RI "sf::Sprite \fBsprite\fP"
.br
.ti -1c
.RI "sf::Texture \fBnormalTexture\fP"
.br
.ti -1c
.RI "sf::Texture \fBtriggeredTexture\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
