.TH "enums.h" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enums.h \- Plik z Enumem opisujacy Stan przyciskow\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBbutton_states\fP { \fBBTN_IDLE\fP = 0, \fBBTN_HOVER\fP, \fBBTN_ACTIVE\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Plik z Enumem opisujacy Stan przyciskow\&. 

Opis stanow przyciskow\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
