.TH "Event.cpp" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Event.cpp \- Plik definicyjny klasy \fBEvent\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Event\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Plik definicyjny klasy \fBEvent\fP\&. 

Plik definicyjny klasy \fBEvent\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
