.TH "EventInstance" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventInstance
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventInstance\fP (sf::RenderWindow &window, \fBPlayer\fP *player, \fBRandom\fP *random)"
.br
.ti -1c
.RI "void \fBGenerateNewEvent\fP ()"
.br
.ti -1c
.RI "void \fBRender\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBProcessEvent\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void EventInstance::ProcessEvent ()"
Generacja nowego Eventu 
.SS "void EventInstance::Render ()"
Aktualizacja Eventu 
.SS "void EventInstance::Update ()"
Obs³uga Eventu 

.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
