.TH "GenDMGUpgrade.cpp" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenDMGUpgrade.cpp \- Plik naglowkowy klasy \fBGenDMGUpgrade\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'GenDMGUpgrade\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Plik naglowkowy klasy \fBGenDMGUpgrade\fP\&. 

Plik naglowkowy klasy \fBGenDMGUpgrade\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
