.TH "GenDMGUpgrade.h" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenDMGUpgrade.h \- Plik naglowkowy klasy \fBGenDMGUpgrade\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Event\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenDMGUpgrade\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Plik naglowkowy klasy \fBGenDMGUpgrade\fP\&. 

Plik naglowkowy klasy genDMGUpgrade\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
