.TH "Player" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEntity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayer\fP (float x, float y, std::string name)"
.br
.ti -1c
.RI "void \fBRender\fP (sf::RenderTarget *renderTarget)"
.br
.ti -1c
.RI "void \fBUpdate\fP (const sf::Vector2f mousePos)"
.br
.ti -1c
.RI "void \fBUpdateButtons\fP ()"
.br
.ti -1c
.RI "void \fBinitializeSkills\fP ()"
.br
.ti -1c
.RI "int \fBCheckCooldown\fP (int index)"
.br
.ti -1c
.RI "void \fBDecrementCooldowns\fP ()"
.br
.ti -1c
.RI "void \fBSetCooldown\fP (int index, int cooldown)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBactiveButtonIndex\fP"
.br
.ti -1c
.RI "std::vector< std::unique_ptr< \fBSkill\fP > > \fBskills\fP"
.br
.ti -1c
.RI "std::vector< int > \fBcooldowns\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
