.TH "Player.cpp" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.cpp \- Plik definicyjny klasy \fBPlayer\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Player\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Plik definicyjny klasy \fBPlayer\fP\&. 

Plik definicyjny klasy \fBPlayer\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
