.TH "Skill.cpp" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Skill.cpp \- Plik definicyjny klasy \fBSkill\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Skill\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Plik definicyjny klasy \fBSkill\fP\&. 

Plik Definicyjny klasy \fBSkill\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
