.TH "Stats" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stats
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBName\fP"
.br
.ti -1c
.RI "int \fBhealth\fP"
.br
.ti -1c
.RI "int \fBmaxHealth\fP"
.br
.ti -1c
.RI "int \fBminDMG\fP"
.br
.ti -1c
.RI "int \fBmaxDMG\fP"
.br
.ti -1c
.RI "int \fBdodge\fP"
.br
.ti -1c
.RI "int \fBaccuracy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
