.TH "Status.h" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Status.h \- Struktura opisujaca statusy\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBStatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struktura opisujaca statusy\&. 

Struktura opisujaca statusy\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
