.TH "UnitFrame.h" 3 "Sun May 16 2021" "SFML_RPG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitFrame.h \- Plik naglowkowy klasy Unitframe\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'enums\&.h'\fP
.br
\fC#include 'Clickable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUnitFrame\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Plik naglowkowy klasy Unitframe\&. 

Plik naglowkowy klasy \fBUnitFrame\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SFML_RPG from the source code\&.
