FightInstance
Enemy* FightInstance::enemy
int FightInstance::enemyAmount
sf::Sound FightInstance::sound
sf::RenderWindow& FightInstance::window
Player* FightInstance::player
Random* FightInstance::random
sf::Clock FightInstance::clock
sf::Time FightInstance::attackCooldown
int FightInstance::turn
std::unique_ptr<Button> FightInstance::attackButton
int FightInstance::activeTargetIndex
int FightInstance::enemiesAmount
Entity** FightInstance::entities
std::vector<bool> FightInstance::prevPressed
std::vector<bool> FightInstance::nowPressed
bool FightInstance::changed
sf::Font FightInstance::font
sf::Text FightInstance::text1
sf::Text FightInstance::text2
sf::Text FightInstance::text3
std::vector<sf::Text> FightInstance::texts
FightInstance::FightInstance(sf::RenderWindow &window, Player *player, Random *random)
FightInstance::~FightInstance()
void FightInstance::Update()
Generacja nowego przeciwnika
Referenced by Fight.
void FightInstance::Render()
Aktualizacja Ekranu Walki
Referenced by Fight.
void FightInstance::Fight()
Sprawdzenie czy walka zostala zakonczona
References CheckIfFinished, OnPressedAttackButton, Render, Update, UpdateEntities.
void FightInstance::UpdateEntities()
Rysowanie Ekranu
Referenced by Fight.
void FightInstance::OnPressedAttackButton()
Aktualizacja jednostek
References CounterAttack.
Referenced by Fight.
void FightInstance::CounterAttack()
Wykonanie Ataku
Referenced by OnPressedAttackButton.
bool FightInstance::CheckIfFinished()
Kontratak przeciwnika
Referenced by Fight.
void FightInstance::GenerateEnemy()
void FightInstance::InitializeText()